from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, List, Optional

from .models import Detection, StackDefinition


HEADER = "Generated by SkillMint. Review before committing."


def generate_all(
    root: Path,
    detections: List[Detection],
    selected_stack_ids: Iterable[str],
    overwrite: bool = False,
    skipped: Optional[List[str]] = None,
) -> List[Path]:
    selected_ids = set(selected_stack_ids)
    selected = [d.stack for d in detections if d.id in selected_ids]
    if not selected:
        return []
    detection_reasons = _detection_reason_map(detections)
    outputs = {
        "AGENTS.md": generate_agents_md(selected, detection_reasons=detection_reasons),
        "CLAUDE.md": generate_claude_md(selected, detection_reasons=detection_reasons),
        ".cursor/rules/project.mdc": generate_cursor_rule(selected, detection_reasons=detection_reasons),
        ".github/copilot-instructions.md": generate_copilot_instructions(selected, detection_reasons=detection_reasons),
    }
    written: List[Path] = []
    for rel_path, content in outputs.items():
        path = root / rel_path
        if path.exists() and not overwrite:
            if skipped is not None:
                skipped.append(f"{rel_path}: already exists")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def preview_generated_skills(detections: List[Detection], selected_stack_ids: Iterable[str]) -> List[tuple[str, str]]:
    """Return readable local skill previews without writing files."""
    selected_ids = set(selected_stack_ids)
    previews: List[tuple[str, str]] = []
    for detection in detections:
        stack = detection.stack
        if detection.id not in selected_ids:
            continue
        previews.append((f".ai/skills/{stack.id}/SKILL.md", generate_internal_skill(stack)))
    return previews


def generate_agents_md(stacks: List[StackDefinition], detection_reasons: Optional[dict[str, List[str]]] = None) -> str:
    return _common_document(
        title="AI Agent Instructions",
        intro="Use these instructions when working inside this repository.",
        stacks=stacks,
        detection_reasons=detection_reasons,
        extra_sections=[
            ("General Rules", [
                "Understand the current project structure before changing files.",
                "Prefer small, focused changes over broad rewrites.",
                "Do not edit secrets, credentials, generated artifacts, or dependency lockfiles unless required.",
                "When changing behavior, update or add tests when practical.",
                "Explain important assumptions in the final response.",
            ]),
        ],
    )


def generate_claude_md(stacks: List[StackDefinition], detection_reasons: Optional[dict[str, List[str]]] = None) -> str:
    return _common_document(
        title="Claude Project Instructions",
        intro="Claude should follow these project-specific rules while assisting with this codebase.",
        stacks=stacks,
        detection_reasons=detection_reasons,
        extra_sections=[
            ("Claude Workflow", [
                "Inspect relevant files before editing.",
                "Keep changes easy to review.",
                "Prefer existing conventions over introducing new patterns.",
                "Run the listed validation commands when possible.",
            ]),
        ],
    )


def generate_cursor_rule(stacks: List[StackDefinition], detection_reasons: Optional[dict[str, List[str]]] = None) -> str:
    body = _common_document(
        title="Cursor Project Rule",
        intro="Apply these rules to all AI-assisted edits in this repository.",
        stacks=stacks,
        detection_reasons=detection_reasons,
        extra_sections=[
            ("Cursor Rules", [
                "Use repository conventions as the source of truth.",
                "Avoid large unrelated edits.",
                "Keep generated code clear and maintainable.",
            ]),
        ],
    )
    return "---\nalwaysApply: true\n---\n\n" + body


def generate_copilot_instructions(stacks: List[StackDefinition], detection_reasons: Optional[dict[str, List[str]]] = None) -> str:
    return _common_document(
        title="GitHub Copilot Instructions",
        intro="Copilot should use these instructions for suggestions in this repository.",
        stacks=stacks,
        detection_reasons=detection_reasons,
        extra_sections=[
            ("Suggestion Guidelines", [
                "Match the style of nearby code.",
                "Prefer safe, explicit, testable changes.",
                "Do not suggest committing secrets or generated output.",
            ]),
        ],
    )


def generate_internal_skill(stack: StackDefinition) -> str:
    lines = [
        f"# {stack.name} Skill",
        "",
        HEADER,
        "",
        "## Purpose",
        f"Help AI coding agents work effectively in {stack.name} projects.",
        "",
    ]
    if stack.commands:
        lines += ["## Common Commands", ""]
        for name, command in stack.commands.items():
            lines.append(f"- {name}: `{command}`")
        lines.append("")
    if stack.rules:
        lines += ["## Rules", ""]
        for rule in stack.rules:
            lines.append(f"- {rule}")
        lines.append("")
    if stack.directories:
        lines += ["## Important Directories", ""]
        for directory in stack.directories:
            lines.append(f"- `{directory}`")
        lines.append("")
    if stack.avoid:
        lines += ["## Avoid Editing", ""]
        for item in stack.avoid:
            lines.append(f"- `{item}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _detection_reason_map(detections: List[Detection]) -> dict[str, List[str]]:
    return {detection.id: detection.reasons for detection in detections if detection.reasons}


def _common_document(
    title: str,
    intro: str,
    stacks: List[StackDefinition],
    extra_sections: List[tuple[str, List[str]]],
    detection_reasons: Optional[dict[str, List[str]]] = None,
) -> str:
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = [f"# {title}", "", HEADER, f"Generated date: {generated}", "", intro, ""]
    lines += ["## Detected Stack", ""]
    for stack in stacks:
        lines.append(f"- {stack.name}")
    lines.append("")

    evidence_lines = []
    if detection_reasons:
        for stack in stacks:
            reasons = detection_reasons.get(stack.id, [])
            if not reasons:
                continue
            evidence_lines.append(f"### {stack.name}")
            evidence_lines.append("")
            for reason in reasons:
                evidence_lines.append(f"- {reason}")
            evidence_lines.append("")
    if evidence_lines:
        lines += ["## Detection Evidence", ""]
        lines.extend(evidence_lines)

    commands = [(stack.name, stack.commands) for stack in stacks if stack.commands]
    if commands:
        lines += ["## Commands", ""]
        for stack_name, stack_commands in commands:
            lines.append(f"### {stack_name}")
            lines.append("")
            for name, command in stack_commands.items():
                lines.append(f"- {name}: `{command}`")
            lines.append("")

    lines += ["## Stack-Specific Rules", ""]
    for stack in stacks:
        if not stack.rules:
            continue
        lines.append(f"### {stack.name}")
        lines.append("")
        for rule in stack.rules:
            lines.append(f"- {rule}")
        lines.append("")

    avoid_items = []
    for stack in stacks:
        avoid_items.extend(stack.avoid)
    if avoid_items:
        lines += ["## Files and Directories to Avoid", ""]
        for item in sorted(set(avoid_items)):
            lines.append(f"- `{item}`")
        lines.append("")

    for section_title, bullets in extra_sections:
        lines += [f"## {section_title}", ""]
        for bullet in bullets:
            lines.append(f"- {bullet}")
        lines.append("")

    skill_lines = []
    for stack in stacks:
        skill_lines.append(f"- {stack.name}: `.ai/skills/{stack.id}/SKILL.md`")
        for external in stack.external_skills:
            skill_lines.append(f"- {external.name}: `{external.install_path}` / {external.url}")
    if skill_lines:
        lines += ["## Installed / Recommended Skills", ""]
        lines.extend(skill_lines)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
